# Generated by Django 4.0.3 on 2022-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
