# Generated by Django 4.0.3 on 2022-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_dishes',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='special_dishes',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
