# Generated by Django 4.0.3 on 2022-03-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_popular_dishes_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='reservation_item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation_item',
            name='table_number',
        ),
        migrations.RemoveField(
            model_name='reservation_item',
            name='time',
        ),
        migrations.CreateModel(
            name='Reservation_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('reservation_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.reservation_item')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Table_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('reservation_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.reservation_item')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('reservation_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.reservation_item')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20)),
                ('reservation_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.reservation_item')),
            ],
        ),
    ]
