# Generated by Django 4.0.3 on 2022-03-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation_received',
            unique_together={('date', 'time', 'table_number')},
        ),
    ]
